#cloud-config
package_update: true
packages:
  - nginx

write_files:
  - path: /etc/nginx/sites-available/default
    owner: root:root
    permissions: '0644'
    content: |
      server {
          listen 80 default_server;
          server_name _;
          root /var/www/html;
          index index.html;
          location / {
              try_files $uri $uri/ =404;
          }
      }

      server {
          listen 443 ssl;
          ssl_certificate /etc/nginx/ssl/webserver2.crt;
          ssl_certificate_key /etc/nginx/ssl/webserver2.key;
          ssl_protocols TLSv1.2 TLSv1.3;
          ssl_ciphers HIGH:!aNULL:!MD5;
          root /var/www/html;
          index index.html;
          location / {
              try_files $uri $uri/ =404;
          }
      }

runcmd:
  - mkdir -p /etc/nginx/ssl/
  - chmod 0600 /etc/nginx/ssl/
  # - systemctl restart nginx